### ISSUE TITLE
Cannot get group invitation from qtox,  is Group chat not implemented yet ?

### ISSUE THREAD

**Issue by HustCoderHu** [evilcorpltd/aTox#1064]

**Comment by emdee-is** [comment]
Is support for NGC groups planned?

**Comment by robinlinden** [comment]
Hi! No form of group support is currently implemented, but it is planned.

It will require some work in jvm-toxcore-{api,c}, so it's not trivial, but I really want it added.

See https://github.com/evilcorpltd/aTox/issues/157 for the issue tracking it. Closing this issue as a duplicate to try to keep everything in one place.
