### ISSUE TITLE
TCP or UDP. Which is more secure?

### ISSUE THREAD

**Issue by fw190d13** [evilcorpltd/aTox#1085]
Hi!

Which of those two is more secure and better from anonymity perspective?

I have tested TCP using Netguard on my Andorid device and I can see that it connects to various servers while the UDP gives just random IP numbers in the log.

Which should I use? Which is better?

**Comment by SiNaPsEr0x** [comment]
udp

**Comment by robinlinden** [comment]
For anonymity, you'll want to use Tox together with Tor. aTox works fine together with e.g. [Orbot](https://play.google.com/store/apps/details?id=org.torproject.android)

UDP tries to create direct connections with your contacts, TCP uses other Tox nodes as TCP relays between you and your contact.

**Comment by SiNaPsEr0x** [comment]
yes... but is very difficult to open everywhere in a ordinary day... torbrowser integrated tor... or simply add socks5 with login e pass possibilty to configure own proxy with tor

**Comment by robinlinden** [comment]
Yeah, it's not super simple and we should make it nicer. :) For now, I have some old instructions I wrote in a different issue:
https://github.com/evilcorpltd/aTox/issues/781#issuecomment-870624824

**Comment by SiNaPsEr0x** [comment]
yes.. on iOS orbot make a VPN ... As iOS works a little differently

**Comment by giiutfff** [comment]
> For anonymity, you'll want to use Tox together with Tor. aTox works fine together with e.g. [Orbot](https://play.google.com/store/apps/details?id=org.torproject.android)

That will be a huge overhead for just being online (idle, not chatting). Since Tox already use a lot power. Might not be ideal for daily usage.

> UDP tries to create direct connections with your contacts, TCP uses other Tox nodes as TCP relays between you and your contact.

Maybe let users choose if they trust given relay? I guess @fw190d13 just finds those servers showing in the network log looks suspicious. Although it's not like any relay could decrypt messages send through them. And any device between client and the relay can detect the data flow. There is no anonymity without a layered network(like Tor) anyway. (correct me if I'm wrong) 

Kind regards

**Comment by fw190d13** [comment]
Hi all!

Thank you for clarifying the situation. I did a bit of testing and on UDP the battery is drained with the speed of water flowing through Niagara Falls. On TCP it is much better but still to fast for my use case so aTOX will be used as a spare tool for the cases when Delta Chat fails to do its job.

**Comment by robinlinden** [comment]
Yeah, since there are no servers involved in Tox and you have to do peer-to-peer stuff like announcing yourself to be online, the pap can't go into the background and the system can't go into deep sleep, so battery drain will be higher.

Thanks for letting me know! :) Closing this as resolved.
