### ISSUE TITLE
Bug utf code

### ISSUE THREAD

**Issue by SiNaPsEr0x** [evilcorpltd/aTox#1087]
Please fix for code utf with Other client

**Comment by robinlinden** [comment]
aTox validates UTF-8 and replaces invalid UTF-8 w/ the UTF-8 replacement character.

What specific problem are you encountering?

I assume you're talking about the clients using a different Toxcore from every other client, sending garbage data after their messages? I am not going to add hacks to my client to handle those clients being broken and sending garbage.

**Comment by SiNaPsEr0x** [comment]
[this](https://github.com/Zoxcore/Antidote/issues/142)

**Comment by SiNaPsEr0x** [comment]
ok ... but not alternative into iOS

**Comment by robinlinden** [comment]
I did start work on bTox because I wanted something like aTox, but for iOS.

I guess there's still value in working on that, so I'll think about cleaning it up and getting it running properly. :)

**Comment by robinlinden** [comment]
As Flutter compiles to web as well, there is a preview of what's implemented so far available [here](https://tox.herokuapp.com/#/). It's not the latest-latest version with Tox integration, but it's enough that you can mess around with the GUI and see if it looks/feels good.
