### ISSUE TITLE
UDP security

### ISSUE THREAD

**Issue by abdkaviani** [evilcorpltd/aTox#1114]
Hi
Can the government identify me when I use UDP?

**Comment by theAkito** [comment]
Greetings 👋🏻

1.
    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
  For more information about that, check out the licence for this project. https://github.com/evilcorpltd/aTox/blob/master/LICENSE
  This means, there is no guarantee for anything. We cannot assure you of anything. You use the software as you see fit, at your own judgment.
2. It depends on your definition of "identification". There are lots of levels of "identification". For example, one can identify you, by what websites you visit with your browser, even if they don't know your address, name or even IP address. You are still identifiable.
  The same way, one can "identify" you just by seeing who you are in contact with. So, even if your traffic is encrypted, it's sometimes enough to see who you are communicating with. This is part of metadata. https://www.justsecurity.org/10311/michael-hayden-kill-people-based-metadata/
3. Depends on your government, its laws & how easy those laws can be circumvented. https://www.visualcapitalist.com/visualizing-corruption-around-the-world/
  If you are in one of those deeply coloured countries, then you can never be sure of anything. Even the lightly coloured USA has global mass surveillance arranged all over the globe.
4. If you have to ask such a question, you are not ready for the task you try to achieve (except you are just asking for fun & not out of actual, real concern).

**Comment by theAkito** [comment]
I hope that answers your question. If you have further questions, please post a new Discussion in the Q&A section of this project.

https://github.com/evilcorpltd/aTox/discussions/categories/q-a

**Comment by robinlinden** [comment]
To add to what theAkito said, if you want privacy when using Tox, you should be combining it with Tor, regardless of TCP/UDP.
See #781 for instructions on how to set it up. :)
