### ISSUE TITLE
Cant build the project 

### ISSUE THREAD

**Issue by daci5455** [evilcorpltd/aTox#1120]
> Task :domain:generateDebugRFile FAILED
> Task :atox:dataBindingMergeDependencyArtifactsDebug FAILED

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':domain:generateDebugRFile'.
> Could not resolve all files for configuration ':domain:debugCompileClasspath'.
   > Could not find org.toktok:tox4j-api_2.11:0.2.3.
     Required by:
         project :domain
   > Could not find org.toktok:tox4j-c_2.11:0.2.3.
     Required by:
         project :domain

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':atox:dataBindingMergeDependencyArtifactsDebug'.
> Could not resolve all files for configuration ':atox:debugCompileClasspath'.
   > Could not find org.toktok:tox4j-api_2.11:0.2.3.
     Required by:
         project :atox > project :domain

**Comment by robinlinden** [comment]
You need to follow the steps in the readme to build the project right now. :P
See: https://github.com/evilcorpltd/aTox#building

If you can't or don't want to build tox4j yourself, you can download it from our GitHub Actions CI here: https://github.com/evilcorpltd/aTox/actions/runs/3825029530#artifacts

**Comment by UtkarshSingh5474** [comment]
The artifact has been expired. :(

**Comment by theAkito** [comment]
> The artifact has been expired. :(

Did you try building the project first?

**Comment by robinlinden** [comment]
It's been about a year, so this question can probably be closed.

If anyone wants a newer non-expired artifact, they can look at newer GitHub Actions runs, but we're not maintaining a link to the latest one here.
