### ISSUE TITLE
run ./scripts/build-i686-linux-android -j$(nproc) release error

### ISSUE THREAD

**Issue by utopia-category** [evilcorpltd/aTox#1146]
aTox/_install/i686-linux-android/lib/libvpx.a(add_noise_sse2.asm.o)(.text+0x46): error: undefined reference to 'rand'

**Comment by robinlinden** [comment]
Can you include more info about what you're doing and what output you're getting from the script?

Just the error isn't enough to tell you what might be going wrong. It works fine in CI, locally on my machine, and in a docker setup I've been messing around with, so it should work fine.

**Comment by utopia-category** [comment]
my environment：centos 7.9,cmake3,android-ndk-r19c,protoc-3.19.6,gradle-7.6.1,openjdk-11+28_linux,android-sdk_r24.4.1-linux.
when i git clone the source from https://github.com/evilcorpltd/aTox.git,and then run 
./scripts/build-host -j$(nproc)
 cp -r ../bin/ _install/host/
./scripts/build-aarch64-linux-android -j$(nproc) release
./scripts/build-arm-linux-androideabi -j$(nproc) release
were right,next 
./scripts/build-i686-linux-android -j$(nproc) release
was error,it's show:
`[ 57%] Building CXX object CMakeFiles/tox4j-c.dir/src/ToxCrypto/encryptsave.cpp.o
[ 60%] Building CXX object CMakeFiles/tox4j-c.dir/src/ToxCrypto/hash.cpp.o
[ 62%] Building CXX object CMakeFiles/tox4j-c.dir/src/ToxCrypto/ToxCrypto.cpp.o
[ 65%] Building CXX object CMakeFiles/tox4j-c.dir/src/tox/av.cpp.o
[ 67%] Building CXX object CMakeFiles/tox4j-c.dir/src/tox/core.cpp.o
[ 70%] Building CXX object CMakeFiles/tox4j-c.dir/src/util/debug_log.cpp.o
[ 72%] Linking CXX shared library libtox4j-c.so
/root/aTox/_install/i686-linux-android/lib/libvpx.a(add_noise_sse2.asm.o)(.text+0x46): error: undefined reference to 'rand'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [libtox4j-c.so] error 1
make[3]: leave directory“/root/aTox/_build/i686-linux-android/tox4j”
make[2]: *** [CMakeFiles/tox4j-c.dir/all] error 2
make[2]: leave directory “/root/aTox/_build/i686-linux-android/tox4j”
make[1]: *** [all] error 2
make[1]: leave directory “/root/aTox/_build/i686-linux-android/tox4j”
make: *** [/root/aTox/_install/i686-linux-android/tox4j.stamp] error 2`

i tried script many time ,same.
