### ISSUE TITLE
Add Serbian localization?

### ISSUE THREAD

**Issue by Strahinja** [evilcorpltd/aTox#1165]
Hi, ten days ago I created a [Serbian localization][1] for aTox, can you please synchronize it from Weblate? Thanks in advance.

[1]: https://hosted.weblate.org/projects/atox/app/sr/

**Comment by robinlinden** [comment]
Updated all translations in #1166 and #1167. Next release will have the Serbian translation, and thank you again! If you want to give it a try before next release, you can download a nightly from https://github.com/evilcorpltd/aTox/actions/runs/6190369327.

**Comment by Strahinja** [comment]
Thank you, I'll close this issue.
