### ISSUE TITLE
Add support for audio calls

### ISSUE THREAD

**Issue by robinlinden** [evilcorpltd/aTox#158]

**Comment by Klagio** [comment]
Please for many is important just a audio chat, For example Trifa is working but only with video (you can't disable video while in a Voice chat): so people are watching my ear when talking :)

**Comment by robinlinden** [comment]
When I write audio calls, I mean audio only. :P There's a separate issue for audio/video calls.

**Comment by zoff99** [comment]
@Klagio you can use TRIfA in the meantime, it has audio only calls.

**Comment by robinlinden** [comment]
Don't advertise your app on this page, @zoff99. Klagio said audio calls in aTox is important because he thinks they don't work well in Trifa.

**Comment by work-flower** [comment]
Hello guys,
Just discovering tox and I think having audio call would be perfect! 
Just wanted to express my interest on audio calls

**Comment by robinlinden** [comment]
Hey there!
Support for audio calls has been merged into master and are being tested right now.
There's a little bit of functionality missing, but that'll be merged soon, so they'll be in the next release for sure! :)

**Comment by work-flower** [comment]
> Hey there!
> Support for audio calls has been merged into master and are being tested right now.
> There's a little bit of functionality missing, but that'll be merged soon, so they'll be in the next release for sure! :)

Great news! Thanks a lot, I should have missed the logs 🤠
