### ISSUE TITLE
Allow usage of encrypted Tox profiles

### ISSUE THREAD

**Issue by robinlinden** [evilcorpltd/aTox#222]
The password field is currently hidden: https://github.com/evilcorpltd/aTox/blob/3f48efe628946a28c0bdc5f5910496eb35788057/app/src/main/res/layout/profile_fragment.xml#L42-L44
Make it visible and allow saving/loading of encrypted Tox profiles.

**Comment by wuniversales** [comment]
It would be good to manage several tox accounts in the same application.
For example, having an account for friends and family, and another for business.

**Comment by robinlinden** [comment]
> It would be good to manage several tox accounts in the same application.
> For example, having an account for friends and family, and another for business.

I was preparing things for that at the start, but haven't continued work on it. It shouldn't be terribly hard to finish. 😃
