### ISSUE TITLE
aTox is repeatedly offered to open http links, registered as a "Browser app"

### ISSUE THREAD

**Issue by anthonybilinski** [evilcorpltd/aTox#274]
Version: master nightly from.. ~5 days ago.

On Android 10.
When I open links from within apps, I get a prompt asking if I would like to use my default browser, or aTox to open the link. If I select aTox, it opens aTox and does nothing.

In settings under Apps & notifications -> Default apps -> Browser app, aTox is one of the options, which is probably the cause.

**Comment by robinlinden** [comment]
Thanks for the report!

Likely something I introduced in 76131f7573aff14f9f6303830ed95d52799d0093 due to the changes in `AndroidMainfest.xml`
https://github.com/evilcorpltd/aTox/blob/36feb18b8a132996981a33fe4da02093e8c65a09/atox/src/main/AndroidManifest.xml#L23-L28
