### ISSUE TITLE
When scrolled up in chat, new messages force scroll to bottom

### ISSUE THREAD

**Issue by anthonybilinski** [evilcorpltd/aTox#275]
Android 10, master nightly from ~2019-11-06.

When scrolled up in a chat, every new message from the friend causes scroll to be moved all the way to the bottom. If you're trying to catch up on messages as a friend types, this makes it almost impossible.

I don't think scroll position should be changed if scrolled up, and only stay at bottom if it was already at bottom.

**Comment by robinlinden** [comment]
Yeah, that's definitely an oversight. Appreciate the report!
