### ISSUE TITLE
Default avatar looks different from no avatar

### ISSUE THREAD

**Issue by anthonybilinski** [evilcorpltd/aTox#277]
Android 10, master nightly from ~2019-11-06.

When I have newly added friends, or imported friends from an old profile, their profile picture shows as the little android head, same as the app logo.

When I see them come online, if they have no avatar, their avatar changes to a white circle.

It would be nice if there was a default avatar for friends with no avatar set, instead of just for friends that you haven't seen come online. Using the app logo (android head for now) in both places seems reasonable.

**Comment by robinlinden** [comment]
Thanks for the report!

Ah, yeah, they should be keeping the Android head as their avatar until they send one to replace it. Do they have an avatar if you have a look in a different client? I am not able to reproduce with neither Echobot nor other contacts without avatars.

**Comment by anthonybilinski** [comment]
Echobot for me does _not_ have this issue. The rest of the contacts I have that I have seen online are all on qTox - so it could be specific qTox behaviour.

I wonder if it's a different between the contact sending a 0-length explicit "no avatar" vs just not sending an avatar at all?

**Comment by robinlinden** [comment]
Ah, yeah, that's it. I don't think I have any qTox contacts without avatars and looking at the code, I don't properly handle 0-sized avatars. I just never realized because uTox and Echobot do it differently. 😁

**Comment by anthonybilinski** [comment]
ah nice :)
qTox sending 0 length when there wasn't a previous avatar might be unnecessary, but I think it's the correct behaviour for deleting an avatar, so I think other clients should also do that in the case where they go from avatar set -> no avatar set, which would probably trigger this white circle behaviour.
