### ISSUE TITLE
Rotating screen on profile creation screen induces crash

### ISSUE THREAD

**Issue by jessica181920** [evilcorpltd/aTox#280]
I was running the "fix chat scrolling" PR build. Opened aTox, tilted phone over, screen went from vertical to horizontal, aTox crashed. Doesn't seem to crash on rotate once a profile is created and you're on the main landing.

**Comment by robinlinden** [comment]
Thank you for the report! I am able to reproduce it, so fixing it hopefully isn't too hard. The call stack isn't very nice though.

**Comment by robinlinden** [comment]
Okay, it wasn't as difficult as it looked at a glance. I was just using the NavController too early, but you'd think that'd explode every time, not just when rotating the phone. That code is getting called every startup.. Thank you again for reporting it!

**Comment by jessica181920** [comment]
> Thank you again for reporting it!

You're welcome :)
