### ISSUE TITLE
Allow exporting chat history

### ISSUE THREAD

**Issue by robinlinden** [evilcorpltd/aTox#292]

**Comment by theAkito** [comment]
I would like to tackle this issue.

**Comment by robinlinden** [comment]
That'd be great! You're very welcome to. :)
If you don't want to, or run into trouble building tox4j, you can download them from our GitHub Actions CI: https://github.com/evilcorpltd/aTox/actions/runs/3349483157
Just extract them in `~` so you end up with a structure like `~/.m2/repository/org/toktok/<tox4j folders here>`

**Comment by robinlinden** [comment]
And if you want to discuss anything related to these things, I'm available on IRC (linked in the readme) and on Tox w/ the Tox ID 3982B009845B210C5A8904B7F540287A424DE029BC1A25C01E022944AB28FC3C4ACEE797596D.
