### ISSUE TITLE
Support for Android 4.4.4

### ISSUE THREAD

**Issue by zgzgng** [evilcorpltd/aTox#350]
For poor people happily using android 4.4.4 will there be a Tox future ?

**Comment by robinlinden** [comment]
What's the actual problem with Android 4.4.4? I already support all versions down to [4.4](https://github.com/evilcorpltd/aTox/blob/master/buildSrc/src/main/kotlin/Dependencies.kt#L40).

Did you try [0.1.0](https://github.com/evilcorpltd/aTox/releases/tag/v0.1.0) and run into some kind of issue?

Apologies for the delayed reply. I've been in a location without internet for the past few days.

**Comment by robinlinden** [comment]
@zgzgng Ping. Did you try aTox with 4.4.4 and run into an issue or did you not know that I already supported versions of Android that old?

**Comment by robinlinden** [comment]
Closing this as invalid as aTox already supports Android 4.4.
