### ISSUE TITLE
"Sending" message is hidden when there are multiple pending messages

### ISSUE THREAD

**Issue by anthonybilinski** [evilcorpltd/aTox#352]
Android 10, running v0.1.0-1

**Repro**:
1) Connect to both wifi and mobile data
1) Send one message from aTox
1) Disconnect from wifi in Android
1) Send two messages from aTox before Tox has reconnected on the new network

**Expected behaviour**:
Any messages not yet delivered are marked as such in chat.

**Observed behaviour**:
No other notices are shown except `Sending...` after the third message. This matches the normal (correct) timestamp behaviour of collapsing duplicate times, but makes it impossible to tell if e.g. the second of three messages was delivered like the first, or pending like the third.

**Comment by robinlinden** [comment]
Ah, whoops. I meant to make an exception for unsent messages when hiding the timestamps. Guess I forgot. :D
