### ISSUE TITLE
Allow cancelling outgoing unsent messages

### ISSUE THREAD

**Issue by wuniversales** [evilcorpltd/aTox#368]

**Comment by robinlinden** [comment]
The current idea is to just resend them as soon as the contact comes online again. Not done yet though. #177 

Allowing a user to cancel sending an outgoing unsent message should also be added though.

**Comment by wuniversales** [comment]
Exactly, that's what I meant ;)

**Comment by robinlinden** [comment]
Haha! 😁 Thank you for the suggestion then!
