### ISSUE TITLE
Allow configuring a proxy / tor / local service

### ISSUE THREAD

**Issue by wuniversales** [evilcorpltd/aTox#374]
It would also be nice if it works locally, without internet.

The idea is to add a proxy, or a tor proxy as optional to the Tox p2p network (Give the option of using a proxy when going out to the internet, obviously this would not be activated on the local network).

**Comment by robinlinden** [comment]
It's on the todo-list! :)

**Comment by Nokia808** [comment]
@robinlinden 
Dear I would like to suggest 2 things:
1) support i2p network.
2) using design like that used by "Privacy Browser" of Android: in the setting of "Privacy Browser" there is "Proxy" section. In the "Proxy" section there are 4 options:

a- none
b- Tor
c- i2p
d- custom

I mean it will be better to make a built-in option for Tor & built-in option for i2p.
The custom option can be used to set other Internet proxy or to set a local network .....
