### ISSUE TITLE
Separate user profile from aTox configuration

### ISSUE THREAD

**Issue by wuniversales** [evilcorpltd/aTox#383]
I mean "imitate qtox", by imitating I mean having ...

- Configuration settings on the one hand

The configuration would have application settings, for example, language settings, theme settings, automatic status change settings to absent, among other settings...

(Qtox config example image)
![image](https://user-images.githubusercontent.com/48658161/78253540-d7d31a80-74f4-11ea-8cb2-e3ea79ed9cc0.png)

- On the other hand, have your own user profile

The user profile would allow you to share the tox id, show and edit your text status, your profile image, your status (Busy, absent...), export options...

(Qtox profile example image)
![image](https://user-images.githubusercontent.com/48658161/78253483-bd993c80-74f4-11ea-924c-7e94a53ee158.png)

For this I suggest the following...

Change main menu options
Instead of showing the options for sharing, exporting and all that, change it like this...

When you click on your nickname, in the text status or profile image, open the user's profile. (The user profile shows the options to edit the profile, nick, states, export tox, show and copy the id, qr code, delete profile, etc ...)

Under the nick, status etc, delete the current menus and finally these menus remain ...

1- Contacts (Show all individual chats and give the option to add friends)
2- Groups (Shows all groups and gives the option to create groups)
3- Settings (Shows general atox settings)
4- Exit

I think this way the design would be more organized. :)

**Comment by robinlinden** [comment]
I agree. :) Most of the GUI is very work-in-progress and I've just put things wherever they were convenient at the time (and the menus would look really empty with 1 item in.) It really needs a lot of cleanup. I'm hoping to steal some design from https://github.com/TokTok/toktok-android as it has a very nice-looking GUI and the UX just feels right. :P
