### ISSUE TITLE
When you click on "Profile" the application stops working

### ISSUE THREAD

**Issue by wuniversales** [evilcorpltd/aTox#411]
I have tested it on android 4.4.2 and android 5.1.1
In both the same error happens, the application closes unexpectedly.
Atox version: v0.3.0
Cheers

**Comment by robinlinden** [comment]
Ah, that sucks. I'm able to reproduce on an older device too. I'll take a look. Appreciate the report! :D

**Comment by wuniversales** [comment]
This seems to be the mistake
`05-07 14:13:47.481 I/am_crash(  682): [6039,0,ltd.evilcorp.atox,13123140,android.content.res.Resources$NotFoundException,Resource ID #0x7f080077,Resources.java,1133]`

**Comment by robinlinden** [comment]
I used a drawable that Android Studio added when creating the project, and it created this file in a folder only available on newer Android versions. :P Whoops!
