### ISSUE TITLE
The default username/status message aren't translatable

### ISSUE THREAD

**Issue by robinlinden** [evilcorpltd/aTox#580]
Should this be fixed? It leaks the user's device language/country, but if the user cares I suppose they can change the name/status message before adding any contacts?

**Comment by JFreegman** [comment]
I can think of two reasonable solutions:

1. Make a "sign up" page on first run where they enter a name and status message. 
2. Make a default name/status message that's always in Enlish

It might also be reasonable to leave it as-is. The default behaviour of Tox already assumes that you at least partially trust your contacts enough to reveal your geolocation (e.g. IP address is revealed by default).

**Comment by robinlinden** [comment]
Sorry, I completely missed this when merging the PR making them translatable.

The background for this issue is that a friend of mine wanted to use aTox with his friends and family, some of which speak no English at all, and wanted it all to be in their native language. I figure that if someone uses Tox and wants to hide their location from their friends, they know to use Tor and to give themselves a unique name/status message that doesn't reveal their location/client.

You're right that the status message probably should be visible on the sign in page so no one misses that it's something you have to change though.
