### ISSUE TITLE
Profile info on long press on a contact

### ISSUE THREAD

**Issue by smaragdus** [evilcorpltd/aTox#625]
There might be added new `Info` command on long press on a contact, which opens Info tab which shows nickname, status and Tox ID. I borrowed the idea about this feature from [TRIfA](https://github.com/zoff99/ToxAndroidRefImpl).

**Comment by robinlinden** [comment]
There is already a profile page if you tap the contact header in the chat, so not sure I want to add another way of getting there. Will think about this one.

**Comment by smaragdus** [comment]
@robinlinden 

> There is already a profile page if you tap the contact header in the chat, so not sure I want to add another way of getting there. Will think about this one.

Somehow I missed this. Context menu command may do the same just like tapping on the contact header. You may close this issue. You choose whether there is any point in adding a context menu command which duplicates an already extant feature.

**Comment by robinlinden** [comment]
There we go! @smaragdus thanks again for the suggestion!

**Comment by smaragdus** [comment]
@robinlinden 

Thanks for the implementation!

Regards
