### ISSUE TITLE
Support location sharing

### ISSUE THREAD

**Issue by ghost** [evilcorpltd/aTox#638]
It would be nice to be able to send geo location into chat 
example link OpenStreetMap

## Plus
The ability to show the interlocutor where you now 
Ability to show on the map specified location 

## Minus
Safety (in more new versions of Android, we can give permission for it, in older versions there are no)

**Comment by robinlinden** [comment]
This won't be integrated into aTox in a way that would require location permissions. Most likely this will use-case will be covered when aTox can receive "shares" from other applications, but I'll leave this issue open until there's a good way of doing this.

**Comment by robinlinden** [comment]
Per my comment, I don't really want this integrated in aTox. This can be done by sharing from an external app to aTox if needed. Any missing options for what share-intents aTox should be reported as separate issues.
