### ISSUE TITLE
Auto Day / Night Theme in time

### ISSUE THREAD

**Issue by xbvrhlmb** [evilcorpltd/aTox#639]
It would be nice if the client could automatically change the day and night the topic at the specified time with the ability to enable this feature in the settings.

with the possibility user of a choice of time

## Example
Day = Light theme
Night = Dark theme

**Comment by escape0707** [comment]
Isn't the follow system option already enough?

**Comment by xbvrhlmb** [comment]
> Isn't the follow system option already enough?

For those who have new version (android 10), enough
But for those who have old versions, (4.4-9) they do not have the ability to switch themes for day and night

**Comment by escape0707** [comment]
Oh I feel so sad about not every device can be configured to adapt an philosophy like ArchLinux have, which is to push everything to newest. And also feels bad that developers will be asked to pay extra efforts implement features to overcome this.
Anyway if you could help by providing a patch, I believe the author will be happy to accept it.

**Comment by robinlinden** [comment]
This is already implemented and handled by the system if you select "follow system".

I just tested it on Android 5.0 (API 21), the oldest device I have available to test on, and it works there and switches from light to dark theme when it's night.

In the version of Android I'm I tested on and the location I'm at, the day/night switch occurs at 22:00. You can test this yourself by just changing the time in Android.

**Comment by robinlinden** [comment]
I spoke with @xbvrhlmb on IRC and we got it working on their phone. Just a misunderstanding. :P
