### ISSUE TITLE
Make Settings Change color Theme and size fonts

### ISSUE THREAD

**Issue by xbvrhlmb** [evilcorpltd/aTox#640]
Such a topic was already, but I will try to duplicate it
It would be nice to be able to choose the color  yourself or add your own # Hex code
and not just default colors

It would also be nice to be able to change the color and size of the text

## Example Screenshot
![Theme_color](https://user-images.githubusercontent.com/43858033/111157748-ec8eae00-859f-11eb-9d3d-3af75677c898.png)

**Comment by robinlinden** [comment]
Duplicate of #620
