### ISSUE TITLE
Option to display contact list as tiles

### ISSUE THREAD

**Issue by ghost** [evilcorpltd/aTox#645]
The ability to sort the list of users by squares or a list.
This is useful for people with weak vision and bad sensor on the 

## Plus
gives user to use more choice in sorting

## Minus
It may take place in the right corner for the sort button

**Comment by robinlinden** [comment]
This won't be worked on anytime soon. PRs welcome if anyone else feels like and can add it without it introducing too much extra complexity.

Re: Weak vision, this is handled by accessibility options built into Android. If aTox doesn't work well with those, that's a separate issue.
