### ISSUE TITLE
Add an "add contact" button to the contact list

### ISSUE THREAD

**Issue by xbvrhlmb** [evilcorpltd/aTox#647]
In many messengers, and even in the Antox there is a right button to add a contact
It is intuitive for normal user 

## Example Screenshot
![add_contact](https://user-images.githubusercontent.com/43858033/111380507-1d103e00-86ad-11eb-85cd-2cd0b6538f8a.png)

**Comment by robinlinden** [comment]
I don't think a menu item that says "add contact" is unintuitive either? I don't really see the value in adding a second button for adding a contact when it's something most users rarely do.

**Comment by robinlinden** [comment]
Likely won't be doing this in the current UI at least. @roihershberg is working on a UI rewamp, and we'll see what things end up looking like there. Closing this as wontfix for now.
