### ISSUE TITLE
Submission to Play Store?

### ISSUE THREAD

**Issue by physkets** [evilcorpltd/aTox#667]
Are there plans to submit this to the play store?

A lot of my friends aren't FOSS or tech enthusiasts, and having them install F-Droid, or use the APK is just another barrier.

If its available on the Play Store, it should make it more accessible. Are you waiting to polish it better, before releasing it there?

**Comment by robinlinden** [comment]
I'm planning on it and have paid the fee and prepared a submission for it. Will hit submit this week and we'll see if/when they approve it.

**Comment by robinlinden** [comment]
Looks like it's done already: https://play.google.com/store/apps/details?id=ltd.evilcorp.atox
Will add the link to the README and tox.chat, and then close this. :)

**Comment by robinlinden** [comment]
PR adding aTox Google Play link to tox.chat here: https://github.com/Tox/tox.chat/pull/236
