### ISSUE TITLE
Long translations can push interactive elements out of bounds

### ISSUE THREAD

**Issue by robinlinden** [evilcorpltd/aTox#710]
Reported by @xbvrhlmb with this screenshot:
![example](https://user-images.githubusercontent.com/8304462/116286946-1b4b9700-a790-11eb-9c30-825f833d27a8.png)

**Comment by xbvrhlmb** [comment]
![1](https://user-images.githubusercontent.com/43858033/116778483-d61eb200-aa7a-11eb-8654-9231290ed95c.png)

Alternatively, make separately headlines and move the settings to the left.

or use per-category example Android Settings About - > more info.
