### ISSUE TITLE
how to use it over tor?

### ISSUE THREAD

**Issue by pujaguja** [evilcorpltd/aTox#781]
im interested to know if i need orbot.and how to setup app and orbot if (neded)

**Comment by pujaguja** [comment]
it works fine now.thanks 😌

**Comment by robinlinden** [comment]
Happy to hear it! Please let me know if you run into any issues or have any feature requests or anything. :)

**Comment by pujaguja** [comment]
it would be nice to have posibility to send  voice msg

**Comment by robinlinden** [comment]
There is a PR adding it, but it's not done, and the original author disappeared, so I'll have to sort it out when I have some time for it.

See: https://github.com/evilcorpltd/aTox/pull/663
