### ISSUE TITLE
Add notification status connecting

### ISSUE THREAD

**Issue by xbvrhlmb** [evilcorpltd/aTox#786]
we have status Connected or Disconnected but not have status Connecting

**Comment by robinlinden** [comment]
That connection status (in the `aTox is running...` notification) matches the connection status reported from the Tox library used for networking, and I'd like to keep it that way, so won't be doing anything with at least right now. I'll reopen it if I change my mind.

See: https://github.com/TokTok/c-toxcore/blob/25a56c354937e9c8c4c50a64c3b4cfc099c34e29/toxcore/tox.h#L993-L1022
