### ISSUE TITLE
Add chat icon to call screen

### ISSUE THREAD

**Issue by xbvrhlmb** [evilcorpltd/aTox#787]
Now Button icon "End Call" and "Microphone" very near to the bottom
especially if the navigation buttons are enabled

Add Icon "Chat" to switch chat dialog
Add Count in Chat icon (count new messenger)

![bottom](https://user-images.githubusercontent.com/43858033/124643224-81901c80-de99-11eb-97b8-6af403d9384d.png)

**Comment by robinlinden** [comment]
Yeah, the buttons need to be moved up a bit, but I had issues with getting the layout to work when trying to do that before merging the call feature; and maybe I'll add a chat button. All it will do it just hit "back" though, since aTox doesn't kill calls when you leave that screen.

**Comment by robinlinden** [comment]
Edited this issue slightly (to only mention the "back to chat" functionality) in order to make tracking easier. I've fixed the padding issue anyway!
