### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by pujaguja** [evilcorpltd/aTox#798]
Hi guys.
Thank you for your time.I have translated app to croatian.can u please add it as soon as posible.
Thanks again :)

**Comment by robinlinden** [comment]
Hi!

Thank you for the translation!

I merge the Weblate translations into the app every few weeks, but until there's a real release, the latest translations are only available in the nightly version found in the topic on IRC, the latest one being robinli.eu/f/atox-0.7.0-pre9.apk, but that was made before you translated the app to Croatian (last night?).

Next nightly will probably be released during the coming week and will contain the Croatian translation! The next real release will be made as soon as I've gotten audio call support working well.

Thank you again for the translation! :D

**Comment by robinlinden** [comment]
(Sent this to you on IRC, but I'll post it here in case anyone else is interested.)

I've now built a new pre-release of 0.7.0 with the Croatian translation (and everything else before 7d496531c323bee344723c42b9d7c4f1ea9195d0) included.

Available at: [aTox 0.7.0 pre-10](http://robinli.eu/f/atox-0.7.0-pre10.apk).
