### ISSUE TITLE
Some files are missing

### ISSUE THREAD

**Issue by webdeveloper510** [evilcorpltd/aTox#801]
Hello All,

I'm using both link i.e 1. https://github.com/evilcorpltd/aTox 2. https://github.com/evilcorpltd/aTox/commit/f735cfd52c1cb71561674257eb0e62a11d7c9360

But now showing me some files are missing there.

Please help me

**Comment by pujaguja** [comment]
![Capture](https://user-images.githubusercontent.com/62655491/126782484-a5205a3d-56f4-454c-9027-8f0233549a25.JPG)
Why does it needs google?

**Comment by webdeveloper510** [comment]
I just clone the code from git and Once I try to run then showing  all screenshot errors.

**Comment by robinlinden** [comment]
We spoke on IRC, but posting my replies here too so it's documented in case anyone else has the same problems.

No screenshot attached, but if I were to guess, I'd say that you missed this part of the readme: https://github.com/evilcorpltd/aTox#build-tox4j

If you're unable to build the libraries yourself, I have uploaded them here as well: https://robinli.eu/f/tox4j-prebuilt.7z

Unzip to `%USERPROFILE%` on Windows (e.g. `C:/Users/robin`) or `$HOME` on Linux (e.g. `/home/robin/`).

**Comment by robinlinden** [comment]
@webdeveloper510 Did using the tox4j files I built for you work any better?

**Comment by robinlinden** [comment]
@webdeveloper510 Ping. Did this resolve the issue you were having?

**Comment by robinlinden** [comment]
I assume this is solved since you stopped responding.
