### ISSUE TITLE
Not able to build the project

### ISSUE THREAD

**Issue by s9iper1** [evilcorpltd/aTox#807]
i followed your guide, 
clone -> run the script -> gradle build 

i get this error

Could not determine the dependencies of task ':domain:preBuild'.
> Could not create task ':domain:fixPaths'.
   > Could not resolve all files for configuration ':domain:needFixing'.
      > Could not find org.toktok:tox4j-c_x86_64-linux-android:0.2.12.
        Searched in the following locations:
          - file:/home/s9iper1/.m2/repository/org/toktok/tox4j-c_x86_64-linux-android/0.2.12/tox4j-c_x86_64-linux-android-0.2.12.pom
          - https://dl.google.com/dl/android/maven2/org/toktok/tox4j-c_x86_64-linux-android/0.2.12/tox4j-c_x86_64-linux-android-0.2.12.pom
          - https://repo.maven.apache.org/maven2/org/toktok/tox4j-c_x86_64-linux-android/0.2.12/tox4j-c_x86_64-linux-android-0.2.12.pom
        Required by:
            project :domain
      > Could not find org.toktok:tox4j-c_i686-linux-android:0.2.12.
        Searched in the following locations:
          - file:/home/s9iper1/.m2/repository/org/toktok/tox4j-c_i686-linux-android/0.2.12/tox4j-c_i686-linux-android-0.2.12.pom
          - https://dl.google.com/dl/android/maven2/org/toktok/tox4j-c_i686-linux-android/0.2.12/tox4j-c_i686-linux-android-0.2.12.pom
          - https://repo.maven.apache.org/maven2/org/toktok/tox4j-c_i686-linux-android/0.2.12/tox4j-c_i686-linux-android-0.2.12.pom
        Required by:
            project :domain
      > Could not find org.toktok:tox4j-c_armv7a-linux-androideabi:0.2.12.
        Searched in the following locations:
          - file:/home/s9iper1/.m2/repository/org/toktok/tox4j-c_armv7a-linux-androideabi/0.2.12/tox4j-c_armv7a-linux-androideabi-0.2.12.pom
          - https://dl.google.com/dl/android/maven2/org/toktok/tox4j-c_armv7a-linux-androideabi/0.2.12/tox4j-c_armv7a-linux-androideabi-0.2.12.pom
          - https://repo.maven.apache.org/maven2/org/toktok/tox4j-c_armv7a-linux-androideabi/0.2.12/tox4j-c_armv7a-linux-androideabi-0.2.12.pom
        Required by:
            project :domain
      > Could not find org.toktok:tox4j-c_aarch64-linux-android:0.2.12.
        Searched in the following locations:
          - file:/home/s9iper1/.m2/repository/org/toktok/tox4j-c_aarch64-linux-android/0.2.12/tox4j-c_aarch64-linux-android-0.2.12.pom
          - https://dl.google.com/dl/android/maven2/org/toktok/tox4j-c_aarch64-linux-android/0.2.12/tox4j-c_aarch64-linux-android-0.2.12.pom
          - https://repo.maven.apache.org/maven2/org/toktok/tox4j-c_aarch64-linux-android/0.2.12/tox4j-c_aarch64-linux-android-0.2.12.pom
        Required by:
            project :domain

**Comment by robinlinden** [comment]
I think you missed this part of the readme: https://github.com/evilcorpltd/aTox#build-tox4j

If you're unable to build the libraries yourself, I have uploaded them here as well: https://robinli.eu/f/tox4j-prebuilt.7z

Unzip to `%USERPROFILE%` on Windows (e.g. `C:/Users/robin`) or `$HOME` on Linux (e.g. `/home/robin/`).

Having to build these libraries manually is unfortunate, but I haven't yet sorted out hosting for them since bintray died. Fixing it is on my backlog: #730.

Please let me know how it goes!

**Comment by s9iper1** [comment]
should i run each script one by one e.g ./scripts/build-host -j$(nproc)
OR  copy all and execute ?

**Comment by robinlinden** [comment]
Running the scripts one-by-one should work! It's what we do in CI. :)

**Comment by s9iper1** [comment]
i copy all and pasted in terminal. here is the output https://paste.ubuntu.com/p/CHS4kRCsSr/

**Comment by s9iper1** [comment]
still i got this 
Failed to resolve: org.toktok:tox4j-api_2.11:0.2.3
Show in Project Structure dialog
Affected Modules: atox, domain 

now i will try prebuilt solution :)

**Comment by robinlinden** [comment]
From your terminal output:
```
/bin/sh: 1: sbt: not found
make: *** [scripts/dependencies.mk:14: /home/s9iper1/work/AndroidStudioProjects/aTox/_install/jvm-sbt-plugins.stamp] Error 127
```
You're missing sbt which means you can't build all dependencies. :P

**Comment by s9iper1** [comment]
It works, Thanks for the help :+1:

**Comment by robinlinden** [comment]
Glad to hear it! :) What are you working on, if you don't mind me asking?

**Comment by s9iper1** [comment]
i am just asked to build this project by employer, will get more info later on.

**Comment by s9iper1** [comment]
sure

**Comment by utopia-category** [comment]
> It works, Thanks for the help 👍

how to make works?
when i run ./gradlew  build,it was show:

What went wrong:
Execution failed for task ':domain:processDebugAndroidTestManifest'.
> Could not resolve all files for configuration ':domain:debugAndroidTestRuntimeClasspath'.
   > Could not find org.toktok:tox4j-api_2.11:0.2.3.
     Required by:
         project :domain
   > Could not find org.toktok:tox4j-c_2.11:0.2.3.
     Required by:
         project :domain

can u help me?

**Comment by richardkamerek** [comment]
This worked, Although the version was different

**Comment by toxifoxy** [comment]
can u please give me the link to the newest repositories or give us a demo to build it after cloning the project from github 
like where i lunch the command of building ?how to install dependencies?etc...
Could not determine the dependencies of task ':domain:preBuild'.
> Could not create task ':domain:fixPaths'.
   > Could not resolve all files for configuration ':domain:needFixing'.
      > Could not find org.toktok:tox4j-c_x86_64-linux-android:0.2.18.
        Searched in the following locations:
          - file:/home/toxi/.m2/repository/org/toktok/tox4j-c_x86_64-linux-android/0.2.18/tox4j-c_x86_64-linux-android-0.2.18.pom
          - https://dl.google.com/dl/android/maven2/org/toktok/tox4j-c_x86_64-linux-android/0.2.18/tox4j-c_x86_64-linux-android-0.2.18.pom
          - https://repo.maven.apache.org/maven2/org/toktok/tox4j-c_x86_64-linux-android/0.2.18/tox4j-c_x86_64-linux-android-0.2.18.pom
        Required by:
            project :domain
      > Could not find org.toktok:tox4j-c_i686-linux-android:0.2.18.
        Searched in the following locations:
          - file:/home/toxi/.m2/repository/org/toktok/tox4j-c_i686-linux-android/0.2.18/tox4j-c_i686-linux-android-0.2.18.pom
          - https://dl.google.com/dl/android/maven2/org/toktok/tox4j-c_i686-linux-android/0.2.18/tox4j-c_i686-linux-android-0.2.18.pom
          - https://repo.maven.apache.org/maven2/org/toktok/tox4j-c_i686-linux-android/0.2.18/tox4j-c_i686-linux-android-0.2.18.pom
        Required by:
            project :domain
      > Could not find org.toktok:tox4j-c_armv7a-linux-androideabi:0.2.18.
        Searched in the following locations:
          - file:/home/toxi/.m2/repository/org/toktok/tox4j-c_armv7a-linux-androideabi/0.2.18/tox4j-c_armv7a-linux-androideabi-0.2.18.pom
          - https://dl.google.com/dl/android/maven2/org/toktok/tox4j-c_armv7a-linux-androideabi/0.2.18/tox4j-c_armv7a-linux-androideabi-0.2.18.pom
          - https://repo.maven.apache.org/maven2/org/toktok/tox4j-c_armv7a-linux-androideabi/0.2.18/tox4j-c_armv7a-linux-androideabi-0.2.18.pom
        Required by:
            project :domain
      > Could not find org.toktok:tox4j-c_aarch64-linux-android:0.2.18.
        Searched in the following locations:
          - file:/home/toxi/.m2/repository/org/toktok/tox4j-c_aarch64-linux-android/0.2.18/tox4j-c_aarch64-linux-android-0.2.18.pom
          - https://dl.google.com/dl/android/maven2/org/toktok/tox4j-c_aarch64-linux-android/0.2.18/tox4j-c_aarch64-linux-android-0.2.18.pom
          - https://repo.maven.apache.org/maven2/org/toktok/tox4j-c_aarch64-linux-android/0.2.18/tox4j-c_aarch64-linux-android-0.2.18.pom
        Required by:
            project :domain
