### ISSUE TITLE
Working / not working  (fails to join node… dunno)

### ISSUE THREAD

**Issue by luffah** [evilcorpltd/aTox#812]
Hello,

  i tried to use aTox  0.6.0 (f-droid) on an Android v6,.
  
  If wifi is not activated before starting the app, it looks like the app don't join any DHT node and then contact can't be added (even after activating wifi).
  Can't kill easily background process.
  Too, 2 minutes after creating a contact, an US number was calling me…

**Comment by robinlinden** [comment]
Hi!

I have fixed some bugs related to aTox not properly connecting to the network when there's no internet at startup, but it's not yet pushed to the app stores. I'm working on finishing audio calls before the next release, but if you want, you can give the [current nightly](https://robinli.eu/f/atox-0.7.0-pre9.apk) a go and see if it resolves the issue you were hitting.

What issue are you having killing the background service? Does the quit button in the menu not work?

That someone called you after you used aTox is an unrelated coincidence. aTox can't even read your phone number, and the only "user data" it sends is what you tell it to send, and it's all only to the intended recipients, e.g. nickname, status message to all contacts, messages you send to contacts (obviously those messages are only sent to the contact you send them to), etc.

You can see its permissions [here](https://github.com/evilcorpltd/aTox/blob/8061b709028d6a9d20ed01c7abfb1eef91eb7449/atox/src/main/AndroidManifest.xml#L5-L9) and [here's](https://stackoverflow.com/a/2480307) what's required to read the phone number (`android.permission.READ_PHONE_STATE`.)

**Comment by robinlinden** [comment]
@luffah Did you try the nightly version? Any other comments? :P

**Comment by luffah** [comment]
No. Sorry.
Lack of time.

**Comment by zellchristensen** [comment]
Just wanted to add that I was having the same issue with the 0.6.0 client not reconnecting if i turned off data and turned it back on later wtih out manually quitting and reopening.  Just tried the 0.7.0 update on github and it auto reconnects in the background without an issue. Hope it's added to f-droid soon :)

**Comment by robinlinden** [comment]
@zellchristensen great to hear that it appears to be resolved. :D We've been working on the FDroid stuff (#933) and made a few fixes for it, so it should be on there soon now! The fixes will be in 0.7.1 which I figure I'll release this week.
