### ISSUE TITLE
No voice or video calls?

### ISSUE THREAD

**Issue by driftywinds** [evilcorpltd/aTox#862]
Hi, I have noticed there is no way to voice or video call from aTox.
I tried calling my aTox profile from my laptop but it never went through. Is there no functionality or am I missing something?

**Comment by robinlinden** [comment]
@driftywinds What do you think of something like https://github.com/evilcorpltd/aTox/discussions/883 ?

**Comment by driftywinds** [comment]
> @driftywinds What do you think of something like #883 ?

after having tested it out, I must say it works like a charm. Absolutely love it, looking forward to video calls also being added!

**Comment by robinlinden** [comment]
Haha! :D I'm very happy you like it, but I meant more doing "pre-release announcements" in the Discussions like that. :P

**Comment by driftywinds** [comment]
> Haha! :D I'm very happy you like it, but I meant more doing "pre-release announcements" in the Discussions like that. :P
oh haha
yes that works amazingly for me! It is easy to find and has a forum for discussion in case of bugs or problems. Perfect. Thank you for your consideration towards my request!!

**Comment by robinlinden** [comment]
Awesome! I'll go ahead and close this issue then, but feel free to keep in touch! I'm always happy to answer questions or receive feature requests or whatever!
