### ISSUE TITLE
Run at boot fix

### ISSUE THREAD

**Issue by roihershberg** [evilcorpltd/aTox#879]
Hello!
I noticed that with the new profile encryption support, the "Run at boot" option doesn't work anymore. I also discovered that there's a similar app to this one called Briar (but with different protocol and Android-only support) which addresses this issue.
When the app receives a broadcast that the boot has been completed, it shows a notification to the user that lets him to sign in again:
![Screenshot_20211203-112946__01](https://user-images.githubusercontent.com/22105369/144590809-a0dffe2c-d79c-4792-ae61-cd69957ee35a.jpg)

aTox could benefit from this functionality too. Maybe a condition can be added to the current mechanism that will check if the profile is encrypted and if it is, then it will show a notification to the user with a click event that will result in the dialog of unlocking the profile.

**Comment by robinlinden** [comment]
Hi! Good report!
The suggestion of showing a notification to unlock the profile is a great idea. :)

**Comment by roihershberg** [comment]
Nice! Thanks

**Comment by robinlinden** [comment]
@roihershberg What do you think of this?
![aTox locked on boot notification](https://user-images.githubusercontent.com/8304462/146462961-b589c1a3-7c38-45fe-bef2-b5ccea546462.png)
Tapping it brings you to the application to let you unlock it. :P

**Comment by roihershberg** [comment]
Amazing! And the explanation is great.

Stay tuned in the next hour for a little thing...  ;)

**Comment by robinlinden** [comment]
Heh, I saw you forked the repo! Looking forward to whatever you're doing! :D

**Comment by roihershberg** [comment]
Haha XD

**Comment by robinlinden** [comment]
@roihershberg If you need any help with anything, Kotlin, git, or whatever, just let me know and I'll do what I can! :P I'm available on the IRC channel linked in the readme ~12h a day as well.

**Comment by roihershberg** [comment]
Thank you!
It took me 15mins to rebase your master XD

**Comment by robinlinden** [comment]
Yeah, I saw you were doing semi-weird things in the GitHub UI, that's why I offered. :P I swear there were only conflicts in like 2 files..

**Comment by roihershberg** [comment]
I know... That's how bad I am with git shell.

**Comment by robinlinden** [comment]
No worries though! If you want I can walk you through how to do it in an easier way. :P
Add me on Tox if you want! `3982B009845B210C5A8904B7F540287A424DE029BC1A25C01E022944AB28FC3C4ACEE797596D`
