### ISSUE TITLE
Scale down the initials in the avatar image when there's more than one letter

### ISSUE THREAD

**Issue by roihershberg** [evilcorpltd/aTox#924]

**Comment by robinlinden** [comment]
All initials in the images should always be the same size, or things will start looking very awkward with different font sizes on different lines in the same widget. I am aware of the initials sometimes overflowing the placeholder avatar and I like that look, but I guess there could be a setting to use a smaller font-size for all initials.

**Comment by roihershberg** [comment]
Yeah. Maybe just decrease the font-size and also limit the initials to the first two characters.

**Comment by robinlinden** [comment]
It should already be limited to 2 characters! :P But yeah, I'm sure we can decrease the font-size a bit.
```
    private fun getInitials(): String {
        val segments = name.split(" ")
        if (segments.size == 1) return segments.first().take(1)
        return segments.first().take(1) + segments[1][0]
    }
```

**Comment by roihershberg** [comment]
Yeah it is!
