### ISSUE TITLE
Call state gets out of sync if a call is rejected while another is ongoing

### ISSUE THREAD

**Issue by roihershberg** [evilcorpltd/aTox#930]

**Comment by robinlinden** [comment]
https://github.com/evilcorpltd/aTox/blob/02dfbd7dc1d3a7ab16d213a6bf6b5ef254af3e7d/atox/src/main/kotlin/ui/chat/ChatFragment.kt#L202-L218

https://github.com/evilcorpltd/aTox/blob/02dfbd7dc1d3a7ab16d213a6bf6b5ef254af3e7d/atox/src/main/kotlin/ui/chat/ChatViewModel.kt#L67-L81

Should be blocking you from initiating calls once you're already in one.

**Comment by roihershberg** [comment]
It turns out it's a different bug. Try being in a call and then reject an incoming call. The ongoing call notification will remain (but the call has crashed) and you will be able to click the call button in another contact.

**Comment by robinlinden** [comment]
Yeah, that makes sense.

https://github.com/evilcorpltd/aTox/blob/02dfbd7dc1d3a7ab16d213a6bf6b5ef254af3e7d/domain/src/main/kotlin/feature/CallManager.kt#L83-L85

This bit needs to check what call is being ended. :P Silly legacy from back when aTox only

**Comment by robinlinden** [comment]
I'll go ahead and fix this since it's a bug introduced in 0.7.0 and we'll have to release a 0.7.1 to fix API 20 and older. :x

**Comment by roihershberg** [comment]
Nice! It's a good thing then that F-Droid failed to build the release. At least you have the possibility of some people using F-Droid while having an old Android so they didn't got the release which presents them with a crash.
