### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [evilcorpltd/aTox#933]
https://monitor.f-droid.org/builds/log/ltd.evilcorp.atox/10#site-footer

Could you please take a look? Thanks!

**Comment by robinlinden** [comment]
Thank you for letting me know it's broken! :P Last time I checked there was an issue with it being built with an too old version of Java, so I figured it was nothing I could help with.

Looks like it's missing the steps to build the native and scala libraries required for aTox:
https://github.com/evilcorpltd/aTox/blob/38d48dd1377bf8f2fabd09e76e9b144d39fec9ae/.github/workflows/ci.yaml#L68-L75

Not sure how the FDroid build process works.. Do I need to do anything to get this set up? Last release it was all handled by people on the FDroid side. :x

**Comment by robinlinden** [comment]
I am looking at publishing these native libraries to Maven Central, but it's nothing I've finished yet, so for now aTox requires everything to be built from source, which I figured would be fine for FDroid. :P

**Comment by linsui** [comment]
You can make an MR for that. Or I'll do that later. Thanks!

**Comment by linsui** [comment]
https://gitlab.com/linsui/fdroiddata/-/jobs/1950307699

The build failed. Could you please take a look?

**Comment by robinlinden** [comment]
Thank you for setting things up!
Looks like it failed to find the `jni.h` header which is weird. It's from `openjdk-11-jdk-headless` which you install.. The include path is pulled in via CMake's [FindJNI](https://cmake.org/cmake/help/latest/module/FindJNI.html) find module. Looks like you can configure it using the `JAVA_HOME` env var.

Try `export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64/`. The header should be in include/ under that folder.

**Comment by linsui** [comment]
It still failed. https://gitlab.com/linsui/fdroiddata/-/jobs/1950415346

**Comment by robinlinden** [comment]
Same issue anyway. :( I'm working on setting up a Dockerfile for building tox4j in so I can try to reproduce it. Until then, do you know if you guys have `cmake-data` installed? Looks like that's where `FindJNI.cmake` comes from. I think you do since I'd expect CMake to tell us there's a find module missing if not, but not 100% sure.

It should also be possible to patch `scripts/build-host` pass CMake hard-coded paths by adding these args to the tox4j_CONFIGURE-line:

```
-DJAVA_AWT_INCLUDE_PATH=/usr/lib/jvm/java-11-openjdk-amd64/include
-DJAVA_AWT_LIBRARY=/usr/lib/jvm/java-11-openjdk-amd64/lib/libjawt.so
-DJAVA_INCLUDE_PATH=/usr/lib/jvm/java-11-openjdk-amd64/include
-DJAVA_INCLUDE_PATH2=/usr/lib/jvm/java-11-openjdk-amd64/include/linux
-DJAVA_JVM_LIBRARY=/usr/lib/jvm/java-11-openjdk-amd64/lib/server/libjvm.so
```
but that really shouldn't be needed.

**Comment by robinlinden** [comment]
Okay, I worked it out. tox4j is currently set up so that unless `openjdk-11-jdk` is installed (it's not enough with `openjdk-11-jdk-headless`), it won't set up the include path needed for `jni.h` as CMake reports that some parts of JNI weren't found.

**Comment by robinlinden** [comment]
FYI, I'll be releasing 0.7.1 soon with a few bug fixes and build improvements. If there's anything that would make your life easier, please let me know. :P

E.g. https://github.com/evilcorpltd/aTox/pull/938 fixes the build with openjdk-11-jdk-headless.

**Comment by linsui** [comment]
I was thinking that you had release the new version so I'm waiting... It still failed with the same error. See https://gitlab.com/linsui/fdroiddata/-/jobs/1954595585. I had changed to openjdk-11-jdk.

**Comment by robinlinden** [comment]
Yeah, 0.7.0 has been released with among other things, audio call support, but I'll need to do a 0.7.1 with some bugfixes. I figured I'd wait until I'd heard from you if there were any build-related things on your wishlist. :P

From that build's output:
```
-- Could NOT find JNI (missing:  JAVA_AWT_INCLUDE_PATH) 
```

From https://cmake.org/cmake/help/v3.22/module/FindJNI.html
```
JAVA_AWT_INCLUDE_PATH
    the include path to jawt.h
```
```
robin@dt:~$ apt-file search jawt.h
openjdk-11-jdk: /usr/lib/jvm/java-11-openjdk-amd64/include/jawt.h
```
And I can see that you're setting `JAVA_HOME` correctly, so not sure what's going on. In my Ubuntu 20.04 Docker setup, installing `openjdk-11-jdk` makes it find JNI even without setting `JAVA_HOME`.. You're running Debian Stretch? I'll flip the Dockerfile to that OS and take a look, but looking at the [file list](https://packages.debian.org/stretch-backports/amd64/openjdk-11-jdk/filelist) of `openjdk-11-jdk`, it should include the same files in the same locations as on Ubuntu 20.04.

Worst case I guess we'll have to wait for 0.7.1 (I'll release it next week, just need to write a changelog and give the translators a few days to get to it if they want), or you could give applying https://github.com/evilcorpltd/aTox/commit/85e933d78385fb551e8e7ef6063b07896f96f57d.patch a try. That's the commit that updates jvm-toxcore-c to work with the headless jdk.

**Comment by linsui** [comment]
I tested with the master but encountered more issues... It finally works with some fixes. https://gitlab.com/linsui/fdroiddata/-/blob/atox/metadata/ltd.evilcorp.atox.yml

Why sbt is needed? I didn't see the scala code... And could you please add some check in makefile so that the install NDK can be found? Thanks!

**Comment by robinlinden** [comment]
Awesome! Thank you for your great work getting it to build! :P

All the Tox jvm bindings (jvm-toxcore-{c, api}) and some of their dependencies are written in Scala, so that's why sbt is needed. It's a bit of a nuisance, but it's how it is right now. Of course! I opened #935 and the plan is to get to resolve it before 0.7.1.

Thank you again!

**Comment by robinlinden** [comment]
@linsui 0.7.1 is now released will use ANDROID_NDK_HOME if set!

**Comment by linsui** [comment]
Builds fine. Thanks!

**Comment by robinlinden** [comment]
@linsui FYI, the symlink weirdness we needed to get libvpx building with the r21 NDK will probably thankfully be going away soon.

#955

**Comment by robinlinden** [comment]
It'll probably be a bit before it's in a release, but it looks like 0.7.2 should be building on FDroid now after your last fix?

**Comment by linsui** [comment]
It builds now. I'll update the metadata after your fix.

**Comment by robinlinden** [comment]
Awesome, thank you!

**Comment by linsui** [comment]
Since it has been autoupdated and this build sync has started, I'll remove those hack in the next version. Thanks!

**Comment by linsui** [comment]
The build failed. https://monitor.f-droid.org/builds/log/ltd.evilcorp.atox/13#site-footer Any idea?

**Comment by robinlinden** [comment]
```
[ 33%] Linking C static library libmsgpackc.a
Error running link command: No such file or directory
CMakeFiles/msgpackc.dir/build.make:198: recipe for target 'libmsgpackc.a' failed
make[3]: *** [libmsgpackc.a] Error 2
make[3]: Leaving directory '/home/vagrant/build/ltd.evilcorp.atox/_build/aarch64-linux-android/msgpack'
```
Not sure why it's failing to link libmsgpack. We're running the exact same commands as the FDroid build in our CI:
https://github.com/evilcorpltd/aTox/blob/54545f6a6c3fc2362183e594ceba3e683105312a/.github/workflows/ci.yaml#L77-L82
https://gitlab.com/fdroid/fdroiddata/-/blob/a0bde6c51171696f4acb35b9f057d849df2a7e00/metadata/ltd.evilcorp.atox.yml#L84-88

I'll try to reproduce the issue in Docker later tonight.

**Comment by linsui** [comment]
Thanks!

**Comment by robinlinden** [comment]
I'm not able to reproduce the error at all in Docker. :(
tox4j Dockerfile: https://github.com/robinlinden/aTox/blob/tox4j-dockerfile/Dockerfile
Successful build: https://github.com/robinlinden/aTox/runs/5296659898?check_suite_focus=true

Is there a different OS I should be basing it on to get something closer to your setup?

**Comment by linsui** [comment]
Maybe you can test with https://gitlab.com/fdroid/docker-executable-fdroidserver

**Comment by robinlinden** [comment]
@linsui https://github.com/evilcorpltd/aTox/pull/1031 removes the dependency on msgpack, so this shouldn't be an issue next release. :P
