### ISSUE TITLE
Support specifying the NDK location using an env var

### ISSUE THREAD

**Issue by robinlinden** [evilcorpltd/aTox#935]
Right now we always require it to be in 
https://github.com/evilcorpltd/aTox/blob/1c4d05637a9c242e67b7b9326cac14eb91ac16cc/scripts/android.mk#L1
which is pretty silly, since I already have an NDK elsewhere for e.g. the Bazel build. It would be nice to support using the same NDK for the from-source build. `ATOX_NDK_HOME`? Reusing `ANDROID_NDK_HOME`?

**Comment by roihershberg** [comment]
If you can make sure that it is the version that is currently required then yes.
